const $=id=>document.getElementById(id);const store=JSON.parse(localStorage.getItem('PAD_UTEQ')||'{}');
const cfg=Object.assign({jefe:'Iván Gutiérrez Bautista',codigo:'EA-F-86',revision:'Rev.01',periodo:'SEP 2026 - AGO 2027'},store.cfg||{});let answers=store.answers||{};
function key(pid,s,c){return `${pid}|${s}|${c}`};function fullName(){return [$("apPat").value,$("apMat").value,$("nombres").value].filter(Boolean).join(' ')}
function go(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
function rows(container,n,type){let h='';for(let i=1;i<=n;i++){if(type==='f')h+=`<div class="grid3"><input placeholder="${i===1?'Grado / estudio':'Estudio '+i}" data-g="f${i}a"><input placeholder="Institución" data-g="f${i}b"><input placeholder="Periodo" data-g="f${i}c"></div>`;if(type==='d')h+=`<div class="grid3"><input placeholder="Institución ${i}" data-g="d${i}a"><input placeholder="Asignaturas / área" data-g="d${i}b"><input placeholder="Periodo" data-g="d${i}c"></div>`;if(type==='l')h+=`<div class="grid3"><input placeholder="Organización ${i}" data-g="l${i}a"><input placeholder="Cargo" data-g="l${i}b"><input placeholder="Periodo" data-g="l${i}c"></div>`}$(container).innerHTML=h}
function init(){CATEGORIES.forEach(c=>$("categoria").add(new Option(c,c)));rows('formacion',7,'f');rows('docencia',4,'d');rows('laboral',5,'l');const p=store.profile||{};['apPat','apMat','nombres','categoria'].forEach(x=>{if(p[x])$(x).value=p[x]});document.querySelectorAll('[data-g]').forEach(x=>x.value=(p.extra||{})[x.dataset.g]||'');$('periodo').value=cfg.periodo;$('jefe').value=cfg.jefe;$('codigo').value=cfg.codigo;$('revisionCal').value=cfg.revision;$('periodoAdmin').value=cfg.periodo;renderPrograms();renderRules()}
function saveProfile(){let extra={};document.querySelectorAll('[data-g]').forEach(x=>extra[x.dataset.g]=x.value);store.profile={apPat:$('apPat').value,apMat:$('apMat').value,nombres:$('nombres').value,categoria:$('categoria').value,extra};saveAll()}
function saveAll(){cfg.periodo=$('periodo').value;store.cfg=cfg;store.answers=answers;localStorage.setItem('PAD_UTEQ',JSON.stringify(store));updateProgress()}
function setAns(pid,s,c,mode){let k=key(pid,s,c),r=answers[k]||{status:'pending',origins:[]};r.status=mode;if(mode==='off'||mode==='pending')r.origins=[];answers[k]=r;if(s<3){let prog=PROGRAMS.find(p=>p.id===pid);if(prog.common){COMMON_GROUPS[prog.common].forEach(other=>{answers[key(other,s,c)]={status:r.status,origins:[...r.origins]}})}}saveAll();renderPrograms()}
function toggleOrigin(pid,s,c,n){let k=key(pid,s,c),r=answers[k]||{status:'pending',origins:[]};if(!['X','XX'].includes(r.status))return;r.origins=r.origins||[];r.origins=r.origins.includes(n)?r.origins.filter(x=>x!==n):[...r.origins,n].sort();answers[k]=r;let prog=PROGRAMS.find(p=>p.id===pid);if(s<3&&prog.common)COMMON_GROUPS[prog.common].forEach(other=>answers[key(other,s,c)]={status:r.status,origins:[...r.origins]});saveAll();renderPrograms()}
function renderPrograms(){let html='';PROGRAMS.forEach(p=>{html+=`<article class="program"><h3>${p.name}<br><small>Salida lateral: ${p.exit}</small></h3>${p.common?`<div class="semester"><div class="common-note">Los cuatrimestres 1, 2 y 3 pertenecen al tronco común ${p.common}. Cualquier cambio se replica automáticamente solo entre los programas correspondientes.</div></div>`:''}`;p.semesters.forEach((sem,s)=>{html+=`<div class="semester"><h4>${s+1}.° cuatrimestre</h4>`;sem.forEach((name,c)=>{let r=answers[key(p.id,s,c)]||{status:'pending',origins:[]};html+=`<div class="course ${r.status==='off'?'off':''}"><div class="name">${name}</div><div class="choices"><button class="disable ${r.status==='off'?'on':''}" onclick="setAns('${p.id}',${s},${c},'off')">✓ Desactivar</button><button class="${r.status==='X'?'on':''}" onclick="setAns('${p.id}',${s},${c},'X')">X</button><button class="${r.status==='XX'?'on':''}" onclick="setAns('${p.id}',${s},${c},'XX')">XX</button></div><div class="origins"><button ${!['X','XX'].includes(r.status)?'disabled':''} class="${r.origins.includes(1)?'on':''}" onclick="toggleOrigin('${p.id}',${s},${c},1)">1 Formación</button><button ${!['X','XX'].includes(r.status)?'disabled':''} class="${r.origins.includes(2)?'on':''}" onclick="toggleOrigin('${p.id}',${s},${c},2)">2 Docencia</button><button ${!['X','XX'].includes(r.status)?'disabled':''} class="${r.origins.includes(3)?'on':''}" onclick="toggleOrigin('${p.id}',${s},${c},3)">3 Laboral</button></div></div>`});html+='</div>'});html+='</article>'});$('programs').innerHTML=html;updateProgress()}
function stats(){let total=0,done=0,invalid=0;PROGRAMS.forEach(p=>p.semesters.forEach((sem,s)=>sem.forEach((_,c)=>{total++;let r=answers[key(p.id,s,c)];if(r&&r.status!=='pending')done++;if(r&&['X','XX'].includes(r.status)&&(!r.origins||!r.origins.length))invalid++})));return{total,done,invalid}}
function updateProgress(){let x=stats(),pct=Math.round(100*x.done/x.total);$('progressText').textContent=`${x.done} de ${x.total} revisadas (${pct}%)`;$('progressBar').style.width=pct+'%'}
function validateAndReview(){saveProfile();let x=stats(),errs=[];if(!fullName())errs.push('Falta el nombre completo del profesor.');if(x.done<x.total)errs.push(`Faltan ${x.total-x.done} asignaturas por revisar.`);if(x.invalid)errs.push(`${x.invalid} asignaturas tienen X/XX pero no tienen origen del conocimiento.`);$('validation').innerHTML=errs.length?`<p class="bad"><b>No se puede finalizar todavía.</b></p><ul>${errs.map(e=>`<li>${e}</li>`).join('')}</ul>`:`<p class="ok"><b>Perfil completo.</b> Todas las asignaturas fueron revisadas. Las desactivadas se imprimirán vacías.</p>`;buildPrint();go('revision')}
function quality(){return `<table class="quality"><tr><td>${cfg.codigo}</td></tr><tr><td>${cfg.revision}</td></tr><tr><td>Fecha: 21-sep-2018</td></tr></table>`}
function buildPrint(){let p=store.profile||{},extra=p.extra||{},head=`<div class="sheetHead"><div><h2>PERFIL DE PROFESOR</h2><b>DIVISIÓN: INDUSTRIAL</b><br><span>PERIODO DE VIGENCIA: ${cfg.periodo}</span></div>${quality()}</div><div class="meta"><b>Nombre del profesor:</b> ${fullName()} &nbsp;&nbsp; <b>Categoría:</b> ${p.categoria||''}</div>`;let pre=`<div class="sheet">${head}<table class="profileTable"><tr><th colspan="3">1. FORMACIÓN PROFESIONAL</th></tr>${Array.from({length:7},(_,i)=>`<tr><td>${extra[`f${i+1}a`]||''}</td><td>${extra[`f${i+1}b`]||''}</td><td>${extra[`f${i+1}c`]||''}</td></tr>`).join('')}<tr><th colspan="3">2. EXPERIENCIA DOCENTE</th></tr>${Array.from({length:4},(_,i)=>`<tr><td>${extra[`d${i+1}a`]||''}</td><td>${extra[`d${i+1}b`]||''}</td><td>${extra[`d${i+1}c`]||''}</td></tr>`).join('')}<tr><th colspan="3">3. EXPERIENCIA LABORAL</th></tr>${Array.from({length:5},(_,i)=>`<tr><td>${extra[`l${i+1}a`]||''}</td><td>${extra[`l${i+1}b`]||''}</td><td>${extra[`l${i+1}c`]||''}</td></tr>`).join('')}</table><div class="sign"><div>${fullName()}<br>Firma del Profesor</div><div>${cfg.jefe}<br>Jefe de Unidad de Coordinación Académica</div></div></div>`;let pages=PROGRAMS.map(pr=>{let max=Math.max(...pr.semesters.map(s=>s.length)),th=pr.semesters.map((s,i)=>`<th colspan="3">${i+1}.° CUATRIMESTRE</th>`).join(''),sub=pr.semesters.map(()=>`<th>Asignatura</th><th>Competencia</th><th>Área</th>`).join(''),rows='';for(let r=0;r<max;r++){rows+='<tr>'+pr.semesters.map((sem,s)=>{let name=sem[r]||'',a=answers[key(pr.id,s,r)]||{status:'pending',origins:[]};return `<td>${name}</td><td>${['X','XX'].includes(a.status)?a.status:''}</td><td>${['X','XX'].includes(a.status)?(a.origins||[]).join(''):''}</td>`}).join('')+'</tr>'}return `<div class="sheet">${head}<div class="meta"><b>COMPETENCIA:</b> XX = ALTO &nbsp; | &nbsp; X = MEDIO &nbsp;&nbsp;&nbsp; <b>Área que le da el conocimiento:</b> formación académica (1), experiencia docente (2), experiencia laboral (3)</div><div class="currTitle">PLAN DE ESTUDIOS: ${pr.name.toUpperCase()} (salida lateral de ${pr.exit})</div><table class="currTable"><tr>${th}</tr><tr>${sub}</tr>${rows}</table><div class="sign"><div>${fullName()}<br>Firma del Profesor</div><div>${cfg.jefe}<br>Jefe de Unidad de Coordinación Académica</div></div></div>`}).join('');$('printArea').innerHTML=pre+pages}
function printProfile(){let x=stats();if(x.done<x.total||x.invalid){alert('El perfil todavía no está completo o tiene materias sin origen del conocimiento.');return}window.print()}
function exportCSV(){let lines=[['Profesor','Categoría','Periodo','Programa','Salida lateral','Cuatrimestre','Asignatura','Estado interno','Competencia impresa','Origen 1','Origen 2','Origen 3']];PROGRAMS.forEach(p=>p.semesters.forEach((sem,s)=>sem.forEach((name,c)=>{let a=answers[key(p.id,s,c)]||{status:'pending',origins:[]};lines.push([fullName(),store.profile?.categoria||'',cfg.periodo,p.name,p.exit,s+1,name,a.status,['X','XX'].includes(a.status)?a.status:'',a.origins.includes(1)?1:'',a.origins.includes(2)?2:'',a.origins.includes(3)?3:''])})));let csv=lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');download('base_madre_perfil_docente.csv','text/csv;charset=utf-8', '\ufeff'+csv)}
function download(n,t,c){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click();URL.revokeObjectURL(a.href)}
function saveAdmin(){cfg.jefe=$('jefe').value;cfg.codigo=$('codigo').value;cfg.revision=$('revisionCal').value;cfg.periodo=$('periodoAdmin').value;$('periodo').value=cfg.periodo;saveAll();alert('Configuración guardada.')}
function downloadCatalog(){download('catalogo_programas.json','application/json',JSON.stringify(PROGRAMS,null,2))}
function renderRules(){$('commonRules').innerHTML=`<p><b>Ingeniería Industrial:</b> cuatrimestres 1-3 sincronizados entre TSU en Procesos Productivos y TSU en Moldeo de Plásticos.</p><p><b>Ingeniería Mecánica:</b> cuatrimestres 1-3 sincronizados entre TSU en Mecánica Industrial, Mecánica Automotriz y Mecánica Moldes y Troqueles.</p><p><b>Sin sincronización:</b> Ingeniería en Mecánica Automotriz / Diseño y Manufactura Automotriz, Nanotecnología y Mantenimiento Industrial.</p>`}
init();
