const CATEGORIES=["Profesor de Tiempo Completo Titular C","Profesor de Tiempo Completo Titular B","Profesor de Tiempo Completo Titular A","Profesor de Tiempo Completo Asociado C","Profesor de Tiempo Completo Asociado B","Profesor de Tiempo Completo Asociado A","Técnico Académico C","Profesor de Asignatura","Profesor de Asignatura (honorarios)"];
const COMMON={
IND:[
["INGLÉS I","DESARROLLO HUMANO Y VALORES","FUNDAMENTOS MATEMÁTICOS","DIBUJO INDUSTRIAL","QUÍMICA BÁSICA","METROLOGÍA","COMUNICACIÓN Y HABILIDADES DIGITALES"],
["INGLÉS II","HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS","CÁLCULO DIFERENCIAL","FÍSICA","PROBABILIDAD Y ESTADÍSTICA","SEGURIDAD, HIGIENE Y MEDIO AMBIENTE","COSTOS DE PRODUCCIÓN"],
["INGLÉS III","DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES","CÁLCULO INTEGRAL","CONTROL DE CALIDAD","PROCESOS DE FABRICACIÓN","ESTUDIO DEL TRABAJO","PROYECTO INTEGRADOR I"]],
MEC:[
["INGLÉS I","DESARROLLO HUMANO Y VALORES","FUNDAMENTOS MATEMÁTICOS","METROLOGÍA","DIBUJO TÉCNICO INDUSTRIAL","SEGURIDAD Y SALUD EN EL TRABAJO","COMUNICACIÓN Y HABILIDADES DIGITALES"],
["INGLÉS II","HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS","CÁLCULO DIFERENCIAL","FÍSICA","PROBABILIDAD Y ESTADÍSTICA","MANUFACTURA I","CIENCIA DE LOS MATERIALES"],
["INGLÉS III","DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES","CÁLCULO INTEGRAL","RESISTENCIA DE MATERIALES","CAD","MANUFACTURA II","PROYECTO INTEGRADOR I"]]
};
const PROGRAMS=[
{id:"auto_diseno",name:"Licenciatura en Ingeniería en Mecánica Automotriz",exit:"Técnico Superior Universitario en Diseño y Manufactura Automotriz",common:null,semesters:[
["INGLÉS I","DESARROLLO HUMANO Y VALORES","FUNDAMENTOS MATEMÁTICOS","DIBUJO ASISTIDO POR COMPUTADORA","SEGURIDAD E HIGIENE INDUSTRIAL","TERMODINÁMICA Y TRANSFERENCIA DE CALOR","COMUNICACIÓN Y HABILIDADES DIGITALES"],
["INGLÉS II","HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS","CÁLCULO DIFERENCIAL","METROLOGÍA","MOTORES DE COMBUSTIÓN INTERNA","PROBABILIDAD Y ESTADÍSTICA","CIENCIA DE LOS MATERIALES"],
["INGLÉS III","DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES","CÁLCULO INTEGRAL","FÍSICA","DIAGNÓSTICO DE SISTEMAS AUTOMOTRICES","SISTEMAS DE GESTIÓN DE CALIDAD Y AMBIENTAL","PROYECTO INTEGRADOR I"],
["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","PROCESOS DE MANUFACTURA","PLANEACIÓN Y CONTROL DE LA PRODUCCIÓN","CALIDAD Y MEJORA CONTINUA","RESISTENCIA DE MATERIALES"],
["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","MANUFACTURA ASISTIDA POR COMPUTADORA","MECANISMOS","REGULACIÓN AUTOMOTRIZ, LEGISLACIÓN Y PATENTES","PROYECTO INTEGRADOR II"]]},
{id:"mec_ind",name:"Licenciatura en Ingeniería Mecánica",exit:"Técnico Superior Universitario en Mecánica Industrial",common:"MEC",semesters:[...COMMON.MEC,["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","MANTENIMIENTO","ANÁLISIS Y SELECCIÓN DE ELEMENTOS MECÁNICOS","VEHÍCULOS AUTOMOTORES","CAM"],["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","SISTEMA DE COMBUSTIÓN Y CALDERAS","CONTROL ELÉCTRICO Y AUTOMATIZACIÓN","AIRE ACONDICIONADO Y REFRIGERACIÓN","PROYECTO INTEGRADOR II"]]},
{id:"mec_moldes",name:"Licenciatura en Ingeniería Mecánica",exit:"Técnico Superior Universitario en Mecánica Moldes y Troqueles",common:"MEC",semesters:[...COMMON.MEC,["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","DISEÑO DE MOLDES Y TROQUELES","GESTIÓN DE LA CALIDAD EN MOLDES Y TROQUELES","PROCESOS DE TROQUELADO Y ESTAMPADO","PROCESOS DE MOLDEO"],["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","MANTENIMIENTO A MOLDES Y TROQUELES","MANUFACTURA AVANZADA A MOLDES Y TROQUELES","METROLOGÍA AVANZADA","PROYECTO INTEGRADOR II"]]},
{id:"mec_auto",name:"Licenciatura en Ingeniería Mecánica",exit:"Técnico Superior Universitario en Mecánica Automotriz",common:"MEC",semesters:[...COMMON.MEC,["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","MOTORES DE COMBUSTIÓN INTERNA","INSTRUMENTACIÓN Y CONTROL AUTOMOTRIZ","SISTEMAS DEL VEHÍCULO I","MANTENIMIENTO AUTOMOTRIZ"],["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","SISTEMA DE INYECCIÓN Y ENCENDIDO","REFRIGERACIÓN Y AIRE ACONDICIONADO AUTOMOTRIZ","SISTEMAS DEL VEHÍCULO II","PROYECTO INTEGRADOR II"]]},
{id:"ind_plasticos",name:"Licenciatura en Ingeniería Industrial",exit:"Técnico Superior Universitario en Moldeo de Plásticos",common:"IND",semesters:[...COMMON.IND,["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","TRANSFORMACIÓN DE PRODUCTOS PLÁSTICOS I","DISEÑO DE PRODUCTOS PLÁSTICOS","ESTRUCTURA Y PROPIEDADES DE LOS POLÍMEROS Y LOS ACEROS","CARACTERIZACIÓN DE POLÍMEROS"],["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","TRANSFORMACIÓN DE PRODUCTOS PLÁSTICOS II","MOLDES","RECICLADO DE POLÍMEROS","PROYECTO INTEGRADOR II"]]},
{id:"ind_procesos",name:"Licenciatura en Ingeniería Industrial",exit:"Técnico Superior Universitario en Procesos Productivos",common:"IND",semesters:[...COMMON.IND,["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","INGENIERÍA DE PLANTA Y ESTUDIO DEL TRABAJO","ADMINISTRACIÓN Y CONTROL DE LA CALIDAD","TECNOLOGÍAS DE TRANSFORMACIÓN DE MATERIALES","INGENIERÍA ECONÓMICA"],["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","ADMINISTRACIÓN Y CONTROL DE OPERACIONES","GESTIÓN AMBIENTAL EN PROCESOS INDUSTRIALES","SISTEMAS DE MANUFACTURA APLICADA","PROYECTO INTEGRADOR II"]]},
{id:"nano",name:"Licenciatura en Ingeniería en Nanotecnología",exit:"Técnico Superior Universitario en Nanotecnología",common:null,semesters:[
["INGLÉS I","DESARROLLO HUMANO Y VALORES","FUNDAMENTOS MATEMÁTICOS","INTRODUCCIÓN A LA NANOTECNOLOGÍA","QUÍMICA GENERAL","TERMODINÁMICA","COMUNICACIÓN Y HABILIDADES DIGITALES"],
["INGLÉS II","HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS","CÁLCULO DIFERENCIAL","FÍSICA","PROBABILIDAD Y ESTADÍSTICA","QUÍMICA ORGÁNICA","METODOLOGÍA DE LA INVESTIGACIÓN"],
["INGLÉS III","DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES","CÁLCULO INTEGRAL","CIENCIA DE LOS MATERIALES","QUÍMICA ANALÍTICA","SÍNTESIS DE NANOMATERIALES","PROYECTO INTEGRADOR I"],
["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","ELECTROQUÍMICA","ÓPTICA Y FENÓMENOS CUÁNTICOS","INCORPORACIÓN DE MATERIALES","NANOBIOLOGÍA"],
["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","NANOMATERIALES","SISTEMAS DE GESTIÓN INTEGRAL","CARACTERIZACIÓN DE MATERIALES I","PROYECTO INTEGRADOR II"]]},
{id:"mantenimiento",name:"Licenciatura en Ingeniería en Mantenimiento Industrial",exit:"Técnico Superior Universitario en Mantenimiento Industrial",common:null,semesters:[
["INGLÉS I","DESARROLLO HUMANO Y VALORES","FUNDAMENTOS MATEMÁTICOS","FUNDAMENTOS DE MANTENIMIENTO","DIBUJO INDUSTRIAL","SEGURIDAD INDUSTRIAL","COMUNICACIÓN Y HABILIDADES DIGITALES"],
["INGLÉS II","HABILIDADES SOCIOEMOCIONALES Y MANEJO DE CONFLICTOS","CÁLCULO DIFERENCIAL","FÍSICA","PROBABILIDAD Y ESTADÍSTICA","GESTIÓN DEL MANTENIMIENTO","TERMODINÁMICA"],
["INGLÉS III","DESARROLLO DEL PENSAMIENTO Y TOMA DE DECISIONES","CÁLCULO INTEGRAL","SISTEMAS ELÉCTRICOS","MÁQUINAS Y MECANISMOS","ELECTRÓNICA ANALÓGICA","PROYECTO INTEGRADOR I"],
["INGLÉS IV","ÉTICA PROFESIONAL","CÁLCULO DE VARIAS VARIABLES","MÁQUINAS ELÉCTRICAS","MANTENIMIENTO A PROCESOS DE MANUFACTURA","ELECTRÓNICA DIGITAL","SISTEMAS NEUMÁTICOS E HIDRÁULICOS"],
["INGLÉS V","LIDERAZGO DE EQUIPOS DE ALTO DESEMPEÑO","ECUACIONES DIFERENCIALES","AUTOMATIZACIÓN Y ROBÓTICA","SISTEMAS TÉRMICOS E INDUSTRIALES","CIENCIA DE LOS MATERIALES","PROYECTO INTEGRADOR II"]]}
];
const COMMON_GROUPS={IND:["ind_plasticos","ind_procesos"],MEC:["mec_ind","mec_moldes","mec_auto"]};


// Horas totales por asignatura en el cuatrimestre, transcritas de los mapas curriculares fuente.
// Para el concentrado se calcula también la carga semanal como horas_totales / 15 semanas.
const PROGRAM_HOURS={
auto_diseno:[
[75,60,105,75,60,75,75],
[75,60,90,75,75,75,75],
[75,60,60,90,90,90,60],
[75,60,75,75,90,75,90],
[75,60,75,90,75,90,60]],
mec_ind:[
[75,60,105,75,75,60,75],
[75,60,90,90,75,75,60],
[75,60,60,75,90,105,60],
[75,60,75,90,75,60,90],
[75,60,75,75,120,60,60]],
mec_moldes:[
[75,60,105,75,75,60,75],
[75,60,90,90,75,75,60],
[75,60,60,75,90,105,60],
[75,60,75,105,60,75,75],
[75,60,75,90,105,60,60]],
mec_auto:[
[75,60,105,75,75,60,75],
[75,60,90,90,75,75,60],
[75,60,60,75,90,105,60],
[75,60,75,90,90,90,45],
[75,60,75,105,60,90,60]],
ind_plasticos:[
[75,60,105,75,75,60,75],
[75,60,90,90,75,75,60],
[75,60,60,90,75,105,60],
[75,60,75,90,60,90,75],
[75,60,75,105,105,45,60]],
ind_procesos:[
[75,60,105,75,75,60,75],
[75,60,90,90,75,75,60],
[75,60,60,90,75,105,60],
[75,60,75,90,90,90,45],
[75,60,75,105,90,60,60]],
nano:[
[75,60,105,60,90,60,75],
[75,60,90,90,75,90,45],
[75,60,60,90,90,90,60],
[75,60,75,75,90,60,90],
[75,60,75,75,75,105,60]],
mantenimiento:[
[75,60,105,60,105,45,75],
[75,60,90,90,75,90,45],
[75,60,60,75,105,90,60],
[75,60,75,60,75,75,105],
[75,60,75,90,75,90,60]]
};
